apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-jdk8
spec:
  selector:
    matchLabels:
      app: wave-jdk8
  replicas: 1
  template:
    metadata:
      labels:
        app: wave-jdk8
    spec:
      containers:
        - name: app
          image: docker.io/serbangilvitu/wave:jdk8
          ports:
            - name: default
              containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: JAVA_OPTS
              value: '-XshowSettings -Xms128m -Xmx1024m'