apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wave.fullname" . }}
  labels:
    {{- include "wave.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "wave.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wave.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          livenessProbe: {{- toYaml .Values.deployment.health.liveness | nindent 12 }}
          readinessProbe: {{- toYaml .Values.deployment.health.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
